### PR TITLE
Workflow for building rpm packages

### PR DESCRIPTION
**Pull request by ps-gill**
As mentioned [here](https://github.com/lyrebird-voice-changer/lyrebird/pull/124#issuecomment-1690782884), adding a GitHub workflow, which will run whenever `lyrebird.spec` is updated. If successful, it will publish a Fedora and CentOS package as workflow artifacts.

Please take a look @sT331h0rs3  @harrego

### CODE REVIEW

**Comment by harrego** [comment]
Incredible addition, thanks again.

Looking at the artifacts I assume I am just able to add the `.rpm` files to the [release files](https://github.com/lyrebird-voice-changer/lyrebird/releases/tag/v1.2.0) but you had mentioned before that "Unfortunately, GitHub does not allow to post RPM files in a plain way" so I just want to make sure doing so is proper.

**Comment by ps-gill** [comment]
> Incredible addition, thanks again.
> 
> Looking at the artifacts I assume I am just able to add the `.rpm` files to the [release files](https://github.com/lyrebird-voice-changer/lyrebird/releases/tag/v1.2.0) but you had mentioned before that "Unfortunately, GitHub does not allow to post RPM files in a plain way" so I just want to make sure doing so is proper.

That is correct. Ideally before creating a release, one would update the spec file, which will run the workflow and publish those RPM files as artifacts.

I might be incorrect but I think what @sT331h0rs3 meant by the inability to post RPM files was within a PR comment. I think, it would be possible to add RPM files as assets while creating a GitHub release.

**Comment by harrego** [comment]
Forgive me, I had attributed that comment to you!

> I think, it would be possible to add RPM files as assets while creating a GitHub release.

That's great, I'll add them to v1.2.0.

**Comment by ps-gill** [comment]
No worries.

**Comment by harrego** [comment]
Updated the README to contain downloads and install instructions see 65c0f89.

**Pull request merged**
